name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Ruff lint
        run: uv run ruff check .
      - name: Ruff format
        run: uv run ruff format --diff .
      # This isn't a general Python lint, this style is just used in this repository
      - name: Prettier format
        run: npx prettier --prose-wrap always --check "**/*.md"

  test:
    name: Run test suites
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv run pytest

  test-win:
    name: Run windows test suites
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Install windows unicode support
        run: uv pip install win-unicode-console
      - name: Run Tests
        run: uv run pytest